language: python
python:
- 3.6
addons:
  apt_packages:
  - libcups2-dev
services:
- mysql
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install -e .
- pip install -r requirements.txt
- pip install flake8
- pip install coveralls
before_script:
- flake8 ambition_rando
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=ambition_rando manage.py test
after_success:
- coveralls
notifications:
  slack:
    secure: Qk2wR2YdbeLQWxdoZJo7wo4eQKSCRDkcCams5Q3Mla5pEfRkIZobZ40ciroWSHt7NYB0frjwodCH8D3IFLaS3eEmEvyc8GaXMyE7yieTnuB5lktnnMKvw4GV60MgQsu6sbsIK7MNj/GsvMUU/89HaaeYxzdW6ulV8EwKz4bAGr5JgstJzxdbWcRrRAdO4cqNuPeZtoKbX1m8H1/6K38SDIdoC4XogHr7Pap0ePzQxItnKOmvY3oHdMyp5nfvOQSGNGcIJ3qoCGO9yG80/rkwpj+MSNTOLS0rjRw/sLvhNRSptzXKezJIPz6ZzEyYV+twLrMUvsUEX+yDnlrGqomUlfd178bBdqvmpbxyxEA5BjUaShMivx+tcHRv9msj7fLT9YkoRJV/vL1z17jicFZunDU4DNM42IS9++ynsobdOLRDk/PD3IaKm27CJDcbHpqOug2XbaUTOwPU1+43imlgT/sj6Wt+orkf53GG33J0WytyFwqQDqBBiezaBVJOY9qUkGNMkYKJCbB/26MAJgLiOKx7acmNw/bZapauihc6dNuxrA6gPWSH0P97JNFNqBArLaKUW19pzZitxvmOa3/WKrmzk/S7zIK6w87XePoThjTXb7ZRLmbGxJWvBS+dUEjGly1Kgmmb5uVeFHZ74Qkx6Nb1WXPJ7/7mcsQCrKJ89Ww=
